### ISSUE TITLE
Öneri

### ISSUE THREAD

**Issue by iscanyc** [SelmanKahya/python-scraper#1]
Selenium kullanmak yerine requests ile daha basit bir şekilde yapılabilirdi, bu tarz projeler yapacak arkadaşların aklında bulunsun.

**Comment by SelmanKahya** [comment]
`requests` kullanarak bahsi gecen URL'i yuklediginde html element'lar render olmuyor, javascript kodu icerisinde gorunuyor. eger deneyip bir sekilde halledebilirsen buradan kodu paylasabilirsin.

**Comment by iscanyc** [comment]
Evet, söz konusu URL'yi inceleme fırsatım anca olabildi. Dediğiniz gibi bir olay, söz konusu `requests` ile yapılması mümkün değil sanırsam.
